import { IAddress } from '../setup/address-interface';
import { IEmployeeGroup } from '../setup/employee-group-interface';
import { IEmployeeLevel } from '../setup/employee-level-interface';
import { EmployeeContract } from './employee-contract';
import { EmployeeEducation } from './employee-education';
import { EmployeeEmployment } from './employee-employment';
import { EmployeeExperience } from './employee-experience';
import { EmployeeFund } from './employee-fund';
import { EmployeeGuarantee } from './employee-guarantee';
import { EmployeeReduceTax } from './employee-reduce-tax';
import { EmployeeSocial } from './employee-social';

export interface IEmployee {
  id: number;
  employeeCode: string;
  titleName: string;
  firstName: string;
  lastName: string;
  displayName: string;
  gender: string;
  weight: number;
  height: number;
  nationalism: string;
  nationality: string;
  religion: string;
  birthDate: Date;
  marry: string;
  military: string;
  idCard: string;
  createdBy: string;
  createdDate: Date;
  editBy: string;
  editDate: Date;
  addresses: IAddress;
  employeeEducations?: EmployeeEducation[];
  employeeContracts?: EmployeeContract[];
  employeeExperiences?: EmployeeExperience[];
  employeeFunds?: EmployeeFund[];
  employeeGuarantees?: EmployeeGuarantee[];
  employeeEmployments?: EmployeeEmployment[];
  employeeReduceTax?: EmployeeReduceTax;
  employeeSocial?: EmployeeSocial;
  employeeGroup: IEmployeeGroup;
  employeeLevel: IEmployeeLevel;
}
